spring.application.name=saltyplank

# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/saltyplank
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# App port
server.port=8080

jwt.secret=SaltyPlankSecretKeyy3216354565VeryLongAndSecureKey